### PR TITLE
Test case and Refactoring.

### PR DESCRIPTION
**Pull request by antrix190**
- Added test cases for RoutingTable.java
- Cleaned code and fixed minor bug.

### CODE REVIEW

**Comment by antrix190** [comment]
@arunans23 Please review.

**Comment by arunans23** [comment]
@antrix190 Your unit tests seems to be very good. But you have changed indentation of existing files which is very hard to review the code.

**Comment by antrix190** [comment]
@arunans23 Cleaned the code a bit to improve readability.

**Comment by antrix190** [comment]
Yes for better readability in my view.

**Comment by arunans23** [comment]
@antrix190 There is no need to change the existing indentation. Please only add the unit test code in your pull request.

**Comment by antrix190** [comment]
Do you have any standard specified for indentation any where?

**Comment by arunans23** [comment]
No. But when you change the existing code, all the commit history will be
altered and we dont know who wrote what

**Pull request closed without merging**
